#!/bin/bash
#PBS -N matrix_parallel
#PBS -o matrix_parallel.out
#PBS -e matrix_parallel.err
#PBS -q short_cpuQ
#PBS -l walltime=0:02:00
#PBS -l select=1:ncpus=1:mpiprocs=1:mem=1gb

# Load the MPI module
module load mpich-3.2

# Set the number of threads for OpenMP
export OMP_NUM_THREADS=1

# Change to the working directory (if needed)
#cd /home/marko.markovic/EsameHPC

# Run the MPI program with 1 MPI process
mpiexec -np 1 ./matrix_parallel 1024